# 1. Import Dependencies

In [3]:
# Import Gym Stuff
import gym
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

# Import Helpers
import numpy as np
import random
import os

# Import Stable Baseline Stuff
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

# 2. Types of Spaces

In [22]:
Discrete(3).sample()

0

In [28]:
Box(0,1, shape=(3,)).sample()

array([0.84976226, 0.8757541 , 0.30529752], dtype=float32)

In [29]:
Box(0,1, shape=(3,3)).sample()

array([[0.7142797 , 0.698802  , 0.27696285],
       [0.04671454, 0.43904433, 0.8456729 ],
       [0.87159777, 0.8283795 , 0.34639746]], dtype=float32)

In [34]:
Tuple((Discrete(3), Box(0,1, shape=(3,1)))).sample()

(1,
 array([[0.05444686],
        [0.85882264],
        [0.98019046]], dtype=float32))

In [36]:
Dict({'height': Discrete(2), 'speed': Box(0,100,shape=(1,))}).sample()

OrderedDict([('height', 1), ('speed', array([85.2225], dtype=float32))])

In [37]:
MultiBinary(4).sample()

array([1, 0, 1, 0], dtype=int8)

In [38]:
MultiDiscrete([5,2,2,5]).sample()

array([0, 0, 0, 2], dtype=int64)

# 3. Building an Environment
- Build an agent to give us the best shower possible
- Randomly temperature changes between 37 to 39

In [ ]:
class ShowerEnv(Env):
    def __init__(self):
        self.action_space = Discrete(3)
        self.observation_space = Box(low=0, high=100, shape=(1,))
        self.state = 38 + random.randint(-3,3)
        self.shower_length = 60
        
    def step(self, action):
        # Apply temp adj
        self.state += action -1
        
        # Decrease shower time
        self.shower_length -= 1
        
        # Calculate Reward
        if self.state >= 37 and self.state <= 39:
            reward = 1
        else:
            reward = -1
            
        if self.shower_length <= 0:
            done = True
        else:
            done = False
            
        info = {}
        
        return self.state, reward, done, info
    
    def render(self):
        # Implement viz
        pass
    def reset(self):
        self.state = np.array([38+random.randint(-3,3)]).astype(float)
        self.shower_length = 60
        return self.state
    