# 1. Import Dependencies

In [1]:
!pip install gym[box2d] pyglet

In [2]:
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
import os

C:\Users\dilan\anaconda3\envs\deep-learning\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\dilan\anaconda3\envs\deep-learning\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\dilan\anaconda3\envs\deep-learning\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
import pygame
import sys

pygame 2.1.0 (SDL 2.0.16, Python 3.9.15)
Hello from the pygame community. https://www.pygame.org/contribute.html


# 2. Test Environment

In [5]:
environment_name = 'CarRacing-v0'
env = gym.make(environment_name)

In [6]:
env.reset()

Track generation: 1112..1394 -> 282-tiles track


C:\Users\dilan\anaconda3\envs\deep-learning\lib\site-packages\pyglet\image\codecs\wic.py:289: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [7]:
env.action_space

Box([-1.  0.  0.], [1. 1. 1.], (3,), float32)

In [8]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [9]:
import pygame
pygame.init()

(5, 0)

In [10]:
episodes = 5
for episode in range(episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Track generation: 1274..1597 -> 323-tiles track
Episode:0 Score:-37.888198757764535
Track generation: 1173..1470 -> 297-tiles track
Episode:1 Score:-32.43243243243289
Track generation: 1070..1341 -> 271-tiles track
Episode:2 Score:-25.925925925926208
Track generation: 1198..1502 -> 304-tiles track
Episode:3 Score:-37.2937293729379
Track generation: 1266..1587 -> 321-tiles track
Episode:4 Score:-37.50000000000063
Track generation: 1191..1493 -> 302-tiles track
Episode:5 Score:-36.8770764119607


# 3. Train Model

In [11]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])

In [12]:
log_path = os.path.join('Training', 'Logs')
model = PPO('CnnPolicy', env, verbose=1, tensorboard_log=log_path)

Using cuda device
Wrapping the env in a VecTransposeImage.


In [13]:
model.learn(total_timesteps=200)

Track generation: 1248..1564 -> 316-tiles track
Logging to Training\Logs\PPO_7
Track generation: 1084..1359 -> 275-tiles track
Track generation: 1071..1343 -> 272-tiles track
-----------------------------
| time/              |      |
|    fps             | 51   |
|    iterations      | 1    |
|    time_elapsed    | 39   |
|    total_timesteps | 2048 |
-----------------------------


# 4. Save Model

In [14]:
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_Driving_Models')

In [15]:
model.save(ppo_path)

In [16]:
del model

In [17]:
model = PPO.load(ppo_path, env)

Wrapping the env in a VecTransposeImage.


# 5. Evaluate and Test

In [18]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

C:\Users\dilan\anaconda3\envs\deep-learning\lib\site-packages\stable_baselines3\common\evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Track generation: 1080..1354 -> 274-tiles track
Track generation: 1110..1393 -> 283-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1179..1478 -> 299-tiles track
Track generation: 1201..1512 -> 311-tiles track
Track generation: 1196..1499 -> 303-tiles track
Track generation: 1168..1464 -> 296-tiles track
Track generation: 1171..1468 -> 297-tiles track
Track generation: 1173..1470 -> 297-tiles track
Track generation: 1030..1292 -> 262-tiles track
Track generation: 1248..1564 -> 316-tiles track
Track generation: 1172..1469 -> 297-tiles track
Track generation: 1060..1329 -> 269-tiles track


(43.85302133187652, 56.474188578046565)

In [19]:
# pygame.quit()
# env.close()

In [20]:
pygame.init()

(5, 0)

In [21]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action, _ = model.predict(obs)
        obs, reward, done, info = env.step(action)
        score += reward
    print('Episodes:{} Score:{}'.format(episode, score))
env.close()

Track generation: 1175..1482 -> 307-tiles track
Track generation: 1276..1599 -> 323-tiles track
Episodes:1 Score:[-54.247894]
Track generation: 1145..1435 -> 290-tiles track
Track generation: 1254..1572 -> 318-tiles track
Episodes:2 Score:[-51.556725]
Track generation: 1136..1424 -> 288-tiles track
Track generation: 1152..1444 -> 292-tiles track
Episodes:3 Score:[-47.73488]
Track generation: 1167..1467 -> 300-tiles track
Track generation: 1138..1426 -> 288-tiles track
Episodes:4 Score:[-49.832455]
Track generation: 1192..1494 -> 302-tiles track
Track generation: 1296..1624 -> 328-tiles track
Episodes:5 Score:[-50.16577]
